### PR TITLE
esm modules, demo page, browser test

### PR DESCRIPTION
**Pull request by bgrosse-midokura**
image

### CODE REVIEW

**Comment by bgrosse-midokura** [comment]
There's a lot of weirdness to the modules. I think some are an acceptable compromise, like the confusing `.js`/`.ts` imports/filenames. Other like raising the `target` to `es2020` shouldn't be taken so lightly. I think I will be able to make two targets/tsconfigs: the current es6/commonjs, and one es2020/es2020. Both can be packed into npm (with es6/commonjs being the default), but the es2020 stuff could be loaded natively in browsers.

**Comment by jbis9051** [comment]
Very much like the idea of having a testable web demo!

**Comment by jbis9051** [comment]
I think the demo page should be separate from the actual browser test. I think we should create an actual test with the testing framework that uses puppeteer to test the library in the browser. The demo page can be separate.

**Comment by bgrosse-midokura** [comment]
Yea I agree, however I would merge this already so that we have some browser test in the CI right now. Then when we want to change to some serious puppeteer setup, we only have to remove that `window.PUPPETEER_PROMISE` from the demo.

**Comment by bgrosse-midokura** [comment]
@bufistov can you take a peek

**Review by bufistov — APPROVED** [review]

**Pull request merged**
