### PR TITLE
Get rid off last dependency

### PR DESCRIPTION
**Pull request by bufistov**

### CODE REVIEW

**Comment by jbis9051** [comment]
I think there is a more efficient way of doing modPow without recursion. I'll post a link soon.

**Comment by bufistov** [comment]
Yess, looking into it as well! :)

**Comment by bgrosse-midokura** [comment]
Make sure to test it in browser, it will be easiest if we merge the other
open PR and then rebase this patch

**Comment by bgrosse-midokura** [comment]
@bufistov do you mind if I rebase this myself, and remove the bigint-mod-arith references in the demo while at it?

**Comment by bufistov** [comment]
Yes, sure. I just wanted to remove recursive calls in the modPow() function. For 4096 bits integers and JS it already matters.
Do you want to merge this and then another PR? I was planning to do it tomorrow night.

**Comment by bgrosse-midokura** [comment]
@bufistov no I just want that the CI runs the browser check too (I just tested locally and it passed). No hurry to merge.

**Comment by bgrosse-midokura** [comment]
@bufistov ok I force-pushed, all good now. You'll have to `get reset --hard origin/bufistov_mod_pow` once.

**Comment by bufistov** [comment]
Done! Please check.

**Comment by jbis9051** [comment]
Could some tests be added for modPow?

**Review by bgrosse-midokura — APPROVED** [review]
@jbis9051 I think it should be covered well enough by existing test suites

**Pull request merged**
