### PR TITLE
rebase

### PR DESCRIPTION
**Pull request by bgrosse-midokura**
comment `/rebase` to rebase a PR

### CODE REVIEW

**Review by bufistov — APPROVED** [review]

**Comment by bufistov** [comment]
Why this PR did not trigger the tests?

**Comment by bgrosse-midokura** [comment]
because they're not in master yet, let's try the command:
/rebase

**Comment by bgrosse-midokura** [comment]
mhh I'm gonna merge it and see

**Comment by bgrosse-midokura** [comment]
@bufistov I need to get access to settings of this repo, to set some secret, so that this action can trigger other actions: https://github.com/midonet/tssrp6a/runs/2047674878?check_suite_focus=true
on monday I'll talk to Agustin.

**Pull request merged**
